### ISSUE TITLE
Can't find a way to run swift methods, tried this repo but getting weird errors.

### ISSUE THREAD

**Issue by universeisblack** [cipolleschi/RNNewArchitectureLibraries#16]
reproduction:
just cloned the repo and add it to a local react native app proejct to test if things are working. but in ios i'm gettin' ```RNCalculatorSpec.h file not found``` error.

i assume that the repo is updated as it's got multiple separate branches.
this's frustrating actually. can't find much information in docs as well.

**Comment by universeisblack** [comment]
```'calculator-Swift.h' file not found```
now getting this error as there's no bridging-header file by default in the repo.
fixed the earlier error by running ```RCT_NEW_ARCH_ENABLED=1 bundle exec pod install```

**Comment by cipolleschi** [comment]
Hi @universeisblack, thanks for trying it out.
The repo has fallen a little behind, as we are now on React Native 0.73 while these examples are all for 0.71.

I don't have much time as of these days to update it, I'm sorry for that. I hope to find some time soon.
Notice that Swift is not officially supported by React Native yet, due to the complexity of the C++ layer that runs under the hood and the lack of complete interoperability between Swift and C++. We are slowing making progress, but the path is still long.

**Comment by SerSerch** [comment]
@universeisblack maybe [my fork](https://github.com/serserm/RNNewArchitectureLibraries/tree/feat/monorepo-073) will help you, but it's Object-C

**Comment by aalimov** [comment]
Hello, wondering if anyone has had a chance to look at the examples more recently. Having similar issues as @universeisblack when trying to follow along on 0.74.

Thank you.

**Comment by SerSerch** [comment]
@aalimov Hi. If you are developing a module, check the [headers](https://github.com/serserm/react-native-turbo-socket/tree/main/packages/react-native-turbo-socket/ios)
this is already my third module (object-c/java) and everything works for me.
in the new architecture, you can write only in object-c. nor can you pass an object to methods
<img width="1400" alt="Знімок екрана 2024-08-02 о 21 11 41" src="https://github.com/user-attachments/assets/e909eae6-7267-4ede-85ed-0a33a7e9ff38">
