### ISSUE TITLE
some questions regarding view manager and some confusion in readme.

### ISSUE THREAD

**Issue by intergalacticspacehighway** [cipolleschi/RNNewArchitectureLibraries#3]
Thank you for creating this repo.

I was looking into the steps of creating a Fabric component and had some confusion so writing it down here.

- This [line](https://github.com/react-native-community/RNNewArchitectureLibraries/tree/feat/back-fabric-comp#fabric-component-update-the-native-ios-code) indicates renaming `RNColoredView.m` to `RNColoredViewManager.mm` but doesn't indicate what to put in `RNColoredViewManager.mm`. I think it's missing the step 8 from [this section](https://github.com/react-native-community/RNNewArchitectureLibraries/tree/feat/back-fabric-comp#native-component-create-the-ios-implementation).

I also have some questions regarding [ViewManager in Fabric example component](https://github.com/react-native-community/RNNewArchitectureLibraries/blob/feat/back-fabric-comp/example-component/ios/RNColoredView/RNColoredViewManager.mm). 

1. Do we need to return view [here](https://github.com/react-native-community/RNNewArchitectureLibraries/blob/feat/back-fabric-comp/example-component/ios/RNColoredView/RNColoredViewManager.mm#L10)? I believe `RNColoredView.mm` also initialises the View. 

2. Do we need to write [setter code here](https://github.com/react-native-community/RNNewArchitectureLibraries/blob/feat/back-fabric-comp/example-component/ios/RNColoredView/RNColoredViewManager.mm#L17) since `RNColoredView.mm` also updates the prop [here](https://github.com/react-native-community/RNNewArchitectureLibraries/blob/feat/back-fabric-comp/example-component/ios/RNColoredView/RNColoredView.mm#L41)?

Let me know If I am getting it wrong. Thanks.

**Comment by cipolleschi** [comment]
Hi @intergalacticspacehighway, thanks for your questions.

Let's go one by one!

> This [line](https://github.com/react-native-community/RNNewArchitectureLibraries/tree/feat/back-fabric-comp#fabric-component-update-the-native-ios-code) indicates renaming RNColoredView.m to RNColoredViewManager.mm but doesn't indicate what to put in RNColoredViewManager.mm. I think it's missing the step 8 from [this section](https://github.com/react-native-community/RNNewArchitectureLibraries/tree/feat/back-fabric-comp#native-component-create-the-ios-implementation).

The rename was actually a typo, fixed by @Titozzz (#5). The point is that iOS needs to run with Objective-C++ and not just Objective-C. While Objective-C files has the `.m` extension, Obj-C++ has the `.mm`.
The implementation of the `RNColoredViewManager` does not have to change: you should already have a `RNColeredViewManager` from [here](https://github.com/react-native-community/RNNewArchitectureLibraries/tree/feat/back-fabric-comp#native-component-create-the-ios-implementation).

> Do we need to return view [here](https://github.com/react-native-community/RNNewArchitectureLibraries/blob/feat/back-fabric-comp/example-component/ios/RNColoredView/RNColoredViewManager.mm#L10)? I believe RNColoredView.mm also initialises the View.

Before Fabric, the ViewManager had the responsibility to instantiate the View that has to be rendered. So, when creating the Native Component, we actually needed that.
With Fabric, we have a dedicated component (the `RNColoredView`) for that. 
Now, if you are interested into a component which only works with the New architecture, you could correctly remove the `- (UIView *)view` method. If you want a component, that works with both, you need it: users who wants to use it in an Old Architecture app will incur in compilation issues without it.

> Do we need to write [setter code here](https://github.com/react-native-community/RNNewArchitectureLibraries/blob/feat/back-fabric-comp/example-component/ios/RNColoredView/RNColoredViewManager.mm#L17) since RNColoredView.mm also updates the prop [here](https://github.com/react-native-community/RNNewArchitectureLibraries/blob/feat/back-fabric-comp/example-component/ios/RNColoredView/RNColoredView.mm#L41)?

Same reasoning as above. You will need both implementation if you want a component which works with both architectures.
If you only need it for the New Architecture, you can remove the setter in the `ViewManager`. However, you still need to expose the property with a `RCT_XXX_PROPERTY` macro, otherwise it won't be visible to the JS environment.

I hope these answers helps. 
Feel free to ask anything!

**Comment by Titozzz** [comment]
@cipolleschi this is extremely interesting, thanks for the detailed explanation

**Comment by intergalacticspacehighway** [comment]
Thank you @cipolleschi for the detailed explanation and @Titozzz for the fix. Makes sense! Closing the issue.
