### ISSUE TITLE
I can't ask questions there. I have no choice but to ask questions here

### ISSUE THREAD

**Issue by jokunhe** [cipolleschi/RNNewArchitectureLibraries#7]
At present, I have tried to use the new architecture in my project, but many third-party libraries cannot be used, and many libraries have been stopped for a long time without maintenance. How can you solve this problem

example ：  react-native-video

**Comment by leotm** [comment]
have you checked out

RE react-native-video
- https://github.com/reactwg/react-native-new-architecture/discussions/6#discussioncomment-2584626
  - https://github.com/react-native-video/react-native-video/issues/2650

otherwise in general
- [Helping migrate React Native libraries to the New Architecture](https://reactnative.dev/blog/2022/06/16/resources-migrating-your-react-native-library-to-the-new-architecture)
- [3rd party libraries - updates and requests](https://github.com/reactwg/react-native-new-architecture/discussions/6)

out of curiosity, where is it you can't ask questions?

**Comment by cortinico** [comment]
Thanks for answering @leotm 🙏 

This is not the right issue tracker for asking question on the New Architecture. You should post them on: https://github.com/reactwg/react-native-new-architecture/

If you don't have access, you can apply for it via the link in the readem
